[build]
builder = "dockerfile"

[deploy]
startCommand = "/bin/bash -c 'gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT'"
healthcheckPath = "/docs"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
